name: Container

on:
  pull_request:
    types: [ closed, assigned, opened, reopened ]

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:13.5.0-alpine3.10
    steps:
      - name: Log node version
        run: |
          node -version
          cat /etc/os-release
