name: Self Hosted Runner Test
on: workflow_dispatch

jobs:
  build:
    runs-on: self-hosted-kalyani
    
    steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r automation/requirements.txt
          
    - name: Test with Pytest
      working-directory: automation\tests\functional\sales
      run: |
        pytest -v -m divisible divisible_tests.py
